import { NextResponse } from 'next/server'
import { Resend } from 'resend'
import { createAdminClient } from '@/lib/supabase/server'
import { generateReportPdf } from '@/lib/client/pdf'
import type { ReportContent } from '@/types/report'

export const runtime = 'nodejs'
// Everything here is a COUNT except the PDF probe, which is a real react-pdf render —
// a couple of seconds warm, more on a cold start. 60s is head-room, not an expectation.
export const maxDuration = 60

// Deliberately lives under /api/client/** for the same reason as the sweep
// (src/app/api/client/internal/sweep/route.ts:7-12): this path inherits the proxy's
// existing bypass, so Vercel's cron reaches the handler. A route anywhere else would hit
// the Supabase session check, find no user, and be redirected to /login — the cron would
// then "succeed" forever while checking nothing. Auth is the CRON_SECRET bearer token,
// and with that env var unset the route refuses every request rather than running open.

// Scheduled hourly in vercel.json (`0 * * * *`), not every 5 minutes like the sweep.
// vercel.json takes no comments — the schema rejects unknown keys — so the reasoning
// lives here: the sweep repairs, this route only reports. Every condition below is
// already defined as at least 10 minutes old (an hour, for paid-undelivered), so running
// more often would not shorten detection of anything; it would only multiply repeat
// alert emails about the same unresolved row and eat the Resend free quota. 24 runs a day
// keeps the worst case — every check failing on every run — under 720 emails a month, well
// inside Resend's free tier. Against a 21-day silent email outage, an hour of latency is noise.

// ---------------------------------------------------------------------------
// Windows and thresholds
// ---------------------------------------------------------------------------

// Everything alertable is bounded to the last 24 hours. Two reasons:
//
// 1. Pre-existing damage. On the day this shipped the table already held 7 analyses
//    stuck in stage2_processing, 5 paid-and-never-delivered rows and 8 failed email
//    sends, all of them days old and none of them recoverable — the sweep itself refuses
//    to touch anything past 24h (SWEEP_MAX_AGE_MS in src/lib/client/rescue.ts). A check
//    that alerted on those would fire on every single run, forever, about rows no action
//    of ours will change. That is the fastest way to train a human to ignore the alarm.
// 2. Once a row falls out of the window it stops alerting on its own, so a burst of
//    failures produces a bounded burst of alerts rather than a permanent one.
//
// Older rows are still counted and returned under `preExisting` in the JSON body, so a
// human opening the URL sees the backlog. They just never page anyone.
export const NEW_DAMAGE_WINDOW_MS = 24 * 60 * 60 * 1000

// A report is marked delivered a moment before its email row is written. Without a grace
// period the check would flag rows that are merely mid-send.
export const EMAIL_LOG_GRACE_MS = 15 * 60 * 1000

// A stage runs at most ~290s before Vercel kills it, and the sweep retries stalls every
// 5 minutes. Anything still sitting in a processing state after 10 minutes has therefore
// already outlived both the timeout and at least one rescue attempt.
export const STALL_THRESHOLD_MS = 10 * 60 * 1000

// Paid, and an hour later still nothing generated. The upload normally moves the row to
// `analyzing` within minutes; an hour means the customer paid and walked into silence.
export const PAID_UNDELIVERED_MS = 60 * 60 * 1000

// Measured: the fixture below renders to 78,091 bytes — 59,017 of that is the embedded
// logo, the rest is font subsets and page content. A missing font throws outright
// (Font.register points at a path react-pdf must read), but a missing logo does not:
// getLogo() swallows the ENOENT and returns null, leaving a ~19KB PDF with a hole where
// the brand mark should be. The floor is what turns that silent degradation into an
// alert. This is the failure `outputFileTracingIncludes` in next.config.ts exists to
// prevent, and the one no unit test can reproduce — locally those files are always there.
export const MIN_PDF_BYTES = 20_000

export const HEALTH_CHECK_SETTING_KEY = 'last_health_check'

// Smallest input that still exercises the whole render path: fonts, logo, markdown
// parsing, section numbering, the disclaimer and the footer.
const PDF_FIXTURE: ReportContent = {
  section_1_general_terrain:
    'Health check probe. This document is generated by the monitoring cron and is never sent to anyone.',
}

type SupabaseAdmin = ReturnType<typeof createAdminClient>

type EmailCheck = {
  ok: boolean
  failedSends: number
  deliveredWithoutLog: number
  latestFailure: string | null
}

type StalledCheck = {
  ok: boolean
  count: number
  analyzing: number
  stage2Processing: number
}

type PaidCheck = { ok: boolean; count: number }
type PdfCheck = { ok: boolean; bytes: number; header: string }
type LivenessCheck = { ok: boolean; writtenAt: string }
type PreExisting = {
  failedSends: number
  stalled: number
  paidUndelivered: number
}

function iso(ms: number): string {
  return new Date(ms).toISOString()
}

/**
 * Counts rows in one status whose stage timestamp falls in a window. Rows with a NULL
 * timestamp are excluded by `lt` — they are invisible to this check by design, because a
 * NULL start time is indistinguishable from a row that was written a millisecond ago.
 */
async function countAnalyses(
  supabase: SupabaseAdmin,
  opts: { status: string; column: string; before: string; after?: string },
): Promise<number> {
  let query = supabase
    .from('client_analyses')
    .select('*', { count: 'exact', head: true })
    .eq('status', opts.status)
    .lt(opts.column, opts.before)

  if (opts.after) query = query.gte(opts.column, opts.after)

  const { count, error } = await query
  if (error) throw new Error(error.message)
  return count ?? 0
}

/**
 * The check that would have caught the 21-day outage on day one.
 *
 * Two signals, both drawn from real customer rows. A synthetic self-send would have
 * stayed green throughout: the old `onboarding@resend.dev` sender delivered perfectly to
 * the account owner and failed only for third parties, so a monitor emailing itself would
 * have reported success for all 21 days while 0 of 7 clients received anything.
 *
 * - `failed` rows are sends the app attempted and Resend rejected.
 * - A completed, delivered report with no email_send_log row at all is worse: the send
 *   never even started, so there is nothing in the log to be red.
 */
async function checkEmailDelivery(supabase: SupabaseAdmin, now: number): Promise<EmailCheck> {
  const windowStart = iso(now - NEW_DAMAGE_WINDOW_MS)

  const {
    data: failures,
    count: failedSends,
    error: failedError,
  } = await supabase
    .from('email_send_log')
    .select('sent_at, error_message, recipient_email', { count: 'exact' })
    .eq('status', 'failed')
    .gte('sent_at', windowStart)
    .order('sent_at', { ascending: false })
    .limit(1)

  if (failedError) throw new Error(failedError.message)

  const { data: delivered, error: deliveredError } = await supabase
    .from('client_analyses')
    .select('id')
    .eq('status', 'completed')
    .gte('report_delivered_at', windowStart)
    .lte('report_delivered_at', iso(now - EMAIL_LOG_GRACE_MS))

  if (deliveredError) throw new Error(deliveredError.message)

  const ids = (delivered ?? []).map((row) => row.id)
  let deliveredWithoutLog = 0

  if (ids.length > 0) {
    const { data: logs, error: logError } = await supabase
      .from('email_send_log')
      .select('analysis_id')
      .in('analysis_id', ids)

    if (logError) throw new Error(logError.message)

    const logged = new Set((logs ?? []).map((row) => row.analysis_id))
    deliveredWithoutLog = ids.filter((id) => !logged.has(id)).length
  }

  const failedCount = failedSends ?? 0

  return {
    ok: failedCount === 0 && deliveredWithoutLog === 0,
    failedSends: failedCount,
    deliveredWithoutLog,
    // The reason is what makes the alert actionable — "sender domain not verified" and
    // "rate limited" call for completely different responses.
    latestFailure: failures?.[0]?.error_message ?? null,
  }
}

/** Analyses that entered a processing state and never came out. */
async function checkStalledAnalyses(supabase: SupabaseAdmin, now: number): Promise<StalledCheck> {
  const before = iso(now - STALL_THRESHOLD_MS)
  const after = iso(now - NEW_DAMAGE_WINDOW_MS)

  const analyzing = await countAnalyses(supabase, {
    status: 'analyzing',
    column: 'analyzing_started_at',
    before,
    after,
  })
  const stage2Processing = await countAnalyses(supabase, {
    status: 'stage2_processing',
    column: 'stage2_started_at',
    before,
    after,
  })

  const count = analyzing + stage2Processing
  return { ok: count === 0, count, analyzing, stage2Processing }
}

/** Money taken, nothing shipped. */
async function checkPaidUndelivered(supabase: SupabaseAdmin, now: number): Promise<PaidCheck> {
  const count = await countAnalyses(supabase, {
    status: 'paid',
    column: 'paid_at',
    before: iso(now - PAID_UNDELIVERED_MS),
    after: iso(now - NEW_DAMAGE_WINDOW_MS),
  })
  return { ok: count === 0, count }
}

/**
 * Renders a real PDF inside the deployed function. This is the only way to catch a broken
 * attachment: the fonts and logo are read off disk in report-pdf-document.tsx and reach
 * the function solely through the per-route `outputFileTracingIncludes` entry in
 * next.config.ts. A missing logo does not throw — it is caught and the PDF renders 59KB
 * lighter — so the size floor, not just the render succeeding, is what makes this real.
 */
async function checkPdfRender(): Promise<PdfCheck> {
  const pdf = await generateReportPdf(PDF_FIXTURE, 'en', false)
  const bytes = pdf.length
  const header = Buffer.from(pdf.subarray(0, 4)).toString('latin1')
  return { ok: header === '%PDF' && bytes >= MIN_PDF_BYTES, bytes, header }
}

/**
 * The one write. A timestamp in `settings` is what proves the cron actually fires and
 * that CRON_SECRET is configured: if every check is green but this value is three days
 * old, the truth is that nothing has been checked in three days. No alert can tell you
 * that — a monitor that is not running sends no alerts. Open item #5 in live-bugs.md.
 */
async function writeLiveness(supabase: SupabaseAdmin, now: number): Promise<LivenessCheck> {
  const writtenAt = iso(now)
  const { error } = await supabase
    .from('settings')
    .upsert({ key: HEALTH_CHECK_SETTING_KEY, value: writtenAt, updated_at: writtenAt }, { onConflict: 'key' })

  if (error) throw new Error(error.message)
  return { ok: true, writtenAt }
}

/** Counted and shown, never alerted on. See NEW_DAMAGE_WINDOW_MS. */
async function countPreExisting(supabase: SupabaseAdmin, now: number): Promise<PreExisting> {
  const windowStart = iso(now - NEW_DAMAGE_WINDOW_MS)

  const { count: failedSends, error } = await supabase
    .from('email_send_log')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'failed')
    .lt('sent_at', windowStart)

  if (error) throw new Error(error.message)

  const analyzing = await countAnalyses(supabase, {
    status: 'analyzing',
    column: 'analyzing_started_at',
    before: windowStart,
  })
  const stage2 = await countAnalyses(supabase, {
    status: 'stage2_processing',
    column: 'stage2_started_at',
    before: windowStart,
  })
  const paidUndelivered = await countAnalyses(supabase, {
    status: 'paid',
    column: 'paid_at',
    before: windowStart,
  })

  return { failedSends: failedSends ?? 0, stalled: analyzing + stage2, paidUndelivered }
}

/**
 * The only alert path left once a problem is found. Reuses the Resend account already
 * wired up for report delivery (src/lib/client/email.ts) instead of adding a new vendor —
 * HEALTH_ALERT_EMAIL is the one new env var this needs.
 */
async function alertProblems(problems: string[]): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.RESEND_FROM_EMAIL
  const to = process.env.HEALTH_ALERT_EMAIL

  if (!apiKey || !from || !to) {
    console.error('health check found problems but alerting is not configured:', problems)
    return
  }

  try {
    const resend = new Resend(apiKey)
    await resend.emails.send({
      from,
      to,
      subject: `[Health check] ${problems.length} problem(s) detected`,
      html: `<ul>${problems.map((p) => `<li>${p}</li>`).join('')}</ul>`,
    })
  } catch (err) {
    console.error('health check alert email failed to send:', err)
  }
}

/**
 * Runs one check and never lets it take the others down. A thrown check is itself a
 * problem worth reporting — a failing query means the health check is blind, which is the
 * state this whole route exists to end.
 */
async function run<T>(
  name: string,
  problems: string[],
  fn: () => Promise<T>,
): Promise<T | { ok: false; error: string }> {
  try {
    return await fn()
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err)
    problems.push(`health check "${name}" could not run: ${detail}`)
    return { ok: false, error: detail }
  }
}

export async function GET(request: Request) {
  const secret = process.env.CRON_SECRET
  const authHeader = request.headers.get('authorization')

  if (!secret || authHeader !== `Bearer ${secret}`) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 })
  }

  const supabase = createAdminClient()
  const now = Date.now()
  const problems: string[] = []

  const email = await run('email_delivery', problems, () => checkEmailDelivery(supabase, now))
  const stalled = await run('stalled_analyses', problems, () => checkStalledAnalyses(supabase, now))
  const paid = await run('paid_undelivered', problems, () => checkPaidUndelivered(supabase, now))
  const pdf = await run('pdf_render', problems, () => checkPdfRender())
  const liveness = await run('cron_liveness', problems, () => writeLiveness(supabase, now))
  const preExisting = await run('pre_existing', problems, () => countPreExisting(supabase, now))

  if ('failedSends' in email && !email.ok) {
    if (email.failedSends > 0) {
      problems.push(
        `${email.failedSends} report email(s) failed to send in the last 24h — latest reason: ${
          email.latestFailure ?? 'not recorded'
        }`,
      )
    }
    if (email.deliveredWithoutLog > 0) {
      problems.push(
        `${email.deliveredWithoutLog} report(s) marked delivered in the last 24h with no email_send_log row at all — the send never started`,
      )
    }
  }

  if ('count' in stalled && !stalled.ok) {
    problems.push(
      `${stalled.count} analysis/analyses stalled over 10 min (analyzing: ${stalled.analyzing}, stage2_processing: ${stalled.stage2Processing}) — the sweep has not rescued them`,
    )
  }

  if ('count' in paid && !paid.ok) {
    problems.push(
      `${paid.count} paid analysis/analyses have shipped nothing after an hour — money taken, no report`,
    )
  }

  if ('bytes' in pdf && !pdf.ok) {
    problems.push(
      `report PDF is broken in this deployment: ${pdf.bytes} bytes, header "${pdf.header}" — fonts or logo are missing from the function filesystem, so every emailed report is an unreadable attachment`,
    )
  }

  if (problems.length > 0) {
    await alertProblems(problems)
  }

  return NextResponse.json(
    {
      ok: problems.length === 0,
      checkedAt: iso(now),
      // Named so nobody reads a green result as "everything is fine, ever".
      alertWindowHours: NEW_DAMAGE_WINDOW_MS / 3_600_000,
      problems,
      checks: { email, stalled, paid, pdf, liveness },
      preExisting,
    },
    // A non-2xx status is what makes Vercel Cron's own failure detection a real backstop —
    // a 200 with problems inside the JSON body was invisible to it.
    { status: problems.length === 0 ? 200 : 500 },
  )
}
